"""Addedo column is_checked to items

Revision ID: 4a16e5845d74
Revises: 0d6200148cb1
Create Date: 2023-09-09 16:45:50.012087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a16e5845d74"
down_revision: Union[str, None] = "0d6200148cb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "items",
        sa.Column(
            "is_checked", sa.INTEGER, autoincrement=False, nullable=True, default=0
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "is_checked")
    # ### end Alembic commands ###
