networks:
  network:
    driver: bridge

services:
  shali_postgres:
    container_name: shali_db
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SHALI_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SHALI_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SHALI_POSTGRES_DB}
      - POSTGRES_SERVER=${SHALI_POSTGRES_SERVER}
      - POSTGRES_PORT=${SHALI_POSTGRES_PORT}
    ports:
      - "${SHALI_POSTGRES_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./shali_db/postgres-data:/var/lib/postgresql/data
    networks:
      - network

  shali_pgadmin:
    container_name: shali_pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${SHALI_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${SHALI_PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${SHALI_PGADMIN_PORT}:80"
    restart: unless-stopped
    networks:
      - network

  shali_be:
    image: shali_be:1.0
    container_name: shali_be
    build: backend
    restart: unless-stopped
    depends_on:
      - shali_postgres
    env_file:
      - .env
    ports:
      - ${SHALI_BACKEND_PORT}:7000
    volumes:
      - ./backend/src:/shali/src
    networks:
      - network
