services:
  postgres:
    container_name: shali_db
    image: postgres:latest
    # user: postgres # ${POSTGRES_USER}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
      # - PGUSER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    restart: always
    volumes:
       - ./shali_db/postgres-data:/var/lib/postgresql/data
    networks:
      - db_network

  pgadmin:
    container_name: shali_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    networks:
      - db_network

  backend:
    container_name: shali_be
    build: ./backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:80
    networks:
      - db_network
    volumes:
      - ./backend/src:/shali/src

networks:
  db_network:
