services:
  postgres:
    container_name: postgres
    image: postgres:latest
    # user: postgres # ${POSTGRES_USER}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
      # - PGUSER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    restart: always
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    networks:
      - db_network
       # - ./postgres-data:/home/postgres/postgresql/data:rw
networks:
  db_network:
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
  #   ports:
  #     - "5050:80"
  #   restart: always